#include "style.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static const char* style = 
    "@import url('https://fonts.googleapis.com/css2?family=Instrument+Serif:ital@0;1&family=Inter:wght@400;500;600&display=swap');\n"
    "\n"
    "\n"
    ":root {\n"
    "    --bg-main: #f9f9fb;          \n"
    "    --text-main: #000000;        \n"
    "    --text-muted: #0000008b;      \n"
    "    --heading-main: #000000;    \n"
    "    --accent: #ff8cbc;          \n"
    "    --bg-code: #61afef00;          \n"
    "   \n"
    "    --border:rgba(0, 0, 0, 0.4) ;\n"
    "    --th-bg: rgba(0, 0, 0, 0.089) ;\n"
    "    \n"
    "    --font-serif: 'Instrument Serif', Georgia, 'Times New Roman', serif;\n"
    "    --font-sans: 'Inter', -apple-system, BlinkMacSystemFont, 'SF Pro Text', system-ui, sans-serif;\n"
    "    --font-mono: monospace;\n"
    "    --content-width: 800px;\n"
    "    --blob-1: rgba(255, 12, 247, 0.145);\n"
    "    --blob-2: rgba(255, 34, 163, 0.12);\n"
    "}\n"
    "\n"
    "\n"
    "\n"
    "\n"
    "/* DARK BLUE THEME \n"
    "\n"
    "\n"
    ":root {\n"
    "    --bg-main: #0b1220;          \n"
    "    --text-main: #e0e0e0;        \n"
    "    --text-muted: #9e9e9e;      \n"
    "    --heading-main: #ffffff;   \n"
    "    --accent: #b9d7f0;          \n"
    "    --bg-code: #61afef00;          \n"
    "   \n"
    "    --border:rgba(203, 213, 225, 0.4) ;\n"
    "    --th-bg: rgba(203, 213, 225, 0.046) ;\n"
    "    \n"
    "    --font-serif: 'Instrument Serif', Georgia, 'Times New Roman', serif;\n"
    "    --font-sans: 'Inter', -apple-system, BlinkMacSystemFont, 'SF Pro Text', system-ui, sans-serif;\n"
    "    --font-mono: monospace;\n"
    "    --content-width: 800px;\n"
    "    --blob-1: rgba(97, 175, 239, 0.12);\n"
    "    --blob-2: rgba(3, 80, 144, 0.12);\n"
    "} \n"
    "\n"
    "*/\n"
    "\n"
    "\n"
    "\n"
    "* {\n"
    "    box-sizing: border-box;\n"
    "}\n"
    "\n"
    "body {\n"
    "\n"
    "    color: var(--text-main);\n"
    "    font-family: var(--font-sans);\n"
    "    line-height: 1.6;\n"
    "    max-width: var(--content-width);\n"
    "    margin: 0 auto;\n"
    "    padding: 2rem 1rem;\n"
    "    font-size: 20px;\n"
    "\n"
    "    background-color: var(--bg-main);\n"
    "    background-image:\n"
    "        radial-gradient(circle at 10% -10%, var(--blob-1), transparent 50%),\n"
    "        radial-gradient(circle at 90% 110%, var(--blob-2), transparent 50%);\n"
    "    background-attachment: fixed;\n"
    "    position: relative;\n"
    "    z-index: 1;\n"
    "\n"
    "\n"
    "}\n"
    "\n"
    "body::before {\n"
    "        content: \"\";\n"
    "        position: fixed;\n"
    "        inset: 0;\n"
    "        z-index: -1;\n"
    "        opacity: 0.04;\n"
    "        pointer-events: none;\n"
    "        background-image: url(\"data:image/svg+xml,%3Csvg viewBox='0 0 512 512' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.7' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)'/%3E%3C/svg%3E\");\n"
    "}\n"
    "\n"
    "\n"
    "h1, h2, h3, h4, h5, h6 {\n"
    "    color: var(--heading-main);\n"
    "    line-height: 1.2;\n"
    "    margin-top: 2em;\n"
    "    margin-bottom: 0.5em;\n"
    "    font-weight: 600;\n"
    "}\n"
    "\n"
    "h1 { \n"
    "    font-size: 2.5rem; \n"
    "    font-style: italic; \n"
    "    font-family: var(--font-serif) ;\n"
    "    margin-bottom: 4rem; \n"
    "}\n"
    "\n"
    "\n"
    "h2 { font-size: 1.8rem;padding-bottom: 0.3em; }\n"
    "h3 { font-size: 1.5rem; }\n"
    "h4 { font-size: 1.25rem; }\n"
    "h5 { font-size: 1rem; }\n"
    "h6 { font-size: 0.875rem; color: var(--text-muted); }\n"
    "\n"
    "p {\n"
    "    margin-top: 0;\n"
    "    margin-bottom: 1.5rem;\n"
    "}\n"
    "\n"
    "a {\n"
    "    color: var(--accent);\n"
    "    text-decoration: none;\n"
    "}\n"
    "\n"
    "a:hover {\n"
    "    text-decoration: underline;\n"
    "}\n"
    "\n"
    "strong { font-weight: bold; }\n"
    "em { font-style: italic; }\n"
    "\n"
    "\n"
    "ul, ol {\n"
    "    margin-top: 0;\n"
    "    margin-bottom: 1.5rem;\n"
    "    padding-left: 2rem;\n"
    "}\n"
    "\n"
    "li {\n"
    "    margin-bottom: 0.5rem;\n"
    "}\n"
    "\n"
    "\n"
    "li ul, li ol {\n"
    "    margin-top: 0.5rem;\n"
    "    margin-bottom: 0;\n"
    "}\n"
    "\n"
    "\n"
    "code {\n"
    "    font-family: var(--font-mono);\n"
    "    background-color: var(--bg-code);\n"
    "    padding: 0.2em 0.4em;\n"
    "    border-radius: 6px;\n"
    "   \n"
    "    font-size: 0.9em;\n"
    "}\n"
    "\n"
    "pre {\n"
    "    background-color: var(--bg-code);\n"
    "    padding: 1rem;\n"
    "    overflow-x: auto;\n"
    "    border-radius: 6px;\n"
    "    border-style: solid;\n"
    "    border-color: var(--border);\n"
    "    border-radius: 3px;\n"
    "    border-width: 1px;\n"
    "    margin-bottom: 1.5rem;\n"
    "}\n"
    "\n"
    "\n"
    "pre code {\n"
    "    background-color: transparent;\n"
    "    padding: 0;\n"
    "    border-radius: 0;\n"
    "    font-size: 0.95em;\n"
    "}\n"
    "\n"
    "\n"
    "blockquote {\n"
    "    margin: 0 0 1.5rem 0;\n"
    "    padding-left: 1rem;\n"
    "    border-left: 4px solid var(--accent);\n"
    "    color: var(--text-muted);\n"
    "    font-style: italic;\n"
    "}\n"
    "\n"
    "blockquote p:last-child {\n"
    "    margin-bottom: 0;\n"
    "}\n"
    "\n"
    "\n"
    "table {\n"
    "    width: 100%;\n"
    "    margin-bottom: 1.5rem;\n"
    "    border: 1px solid var(--border); \n"
    "    border-collapse: separate;  \n"
    "    border-spacing: 0;          \n"
    "    border-radius: 10px;                       \n"
    "    overflow: hidden;\n"
    "}\n"
    "\n"
    "th, td {\n"
    "    padding: 0.75rem;\n"
    "    text-align: left;\n"
    "\n"
    "    border-bottom: 1px solid var(--border);\n"
    "    \n"
    "}\n"
    "\n"
    "th {\n"
    "    font-weight: 600;\n"
    "    color: var(--heading-main);\n"
    "    background-color: var(--th-bg);\n"
    "}\n"
    "\n"
    "\n"
    "th:last-child, td:last-child {\n"
    "    border-right: none;\n"
    "}\n"
    "\n"
    "tr:last-child td {\n"
    "    border-bottom: none;\n"
    "}\n"
    "\n"
    "\n"
    "img {\n"
    "    max-width: 100%;\n"
    "    height: auto;\n"
    "    display: block;\n"
    "    margin: 1.5rem auto;\n"
    "    border-radius: 4px;\n"
    "}\n"
    "\n"
    "hr {\n"
    "    border: 0;\n"
    "    height: 1px;\n"
    "    background-color: var(--border);\n"
    "    margin: 2.5rem 0;\n"
    "}";


const char* get_css(){
    return style;
}






